<?
#$lang_str["importance:name"]="Importance";
#$lang_str["importance:global"]="global";
#$lang_str["importance:international"]="international";
#$lang_str["importance:national"]="national";
#$lang_str["importance:regional"]="regional";
#$lang_str["importance:urban"]="urban";
#$lang_str["importance:suburban"]="suburban";
#$lang_str["importance:local"]="local";
