#!/bin/bash

# This script is used in the live database
# The import happens in a new database called 'gisnew' 
# When everything is finished the old database 'gis' is renamed to 'gisold' (in
# case something went wrong, it can be drop later or when do_all_live is called
# the next time) and 'gisnew' renamed to 'gis'

export ROOT_PATH=/osm/osm
export SOFTWARE_PATH=/osm/osm/software
export DB_NAME=gisnew

echo "=== Starting Database reload. Press key to continue."
read

echo "* SVN - Update database import"
svn update src/

echo "* Download new OSM-File"
cd $ROOT_PATH/data
wget -N http://download.geofabrik.de/osm/europe.osm.bz2
wget -N http://tile.openstreetmap.org/world_boundaries-spherical.tgz
wget -N http://tile.openstreetmap.org/shoreline_300.tar.bz2
wget -N http://tile.openstreetmap.org/processed_p.tar.bz2

echo "* Importing to Database"
echo "- Shapefiles"
cd $ROOT_PATH/data
tar xzf world_boundaries-spherical.tgz
mkdir world_boundaries/
unzip processed_p.zip
mv coastlines/* world_boundaries/
rmdir coastlines
tar xjf shoreline_300.tar.bz2 -C world_boundaries

echo "- prepare osm2pgsql"
psql -d gis -c "drop database gisold"
psql -d gis -c "drop database gisnew"
psql -d gis -c "create database gisnew"
psql -d gisnew -c "create language plpgsql"
psql  -f /usr/share/postgresql/9.0/contrib/postgis-1.5/postgis.sql
psql  -f /usr/share/postgresql/9.0/contrib/_int.sql
psql  -f /usr/share/postgresql/9.0/contrib/hstore.sql
psql  -f /usr/share/postgresql/9.0/contrib/spatial_ref_sys.sql
psql  -f /usr/share/postgresql/9.0/contrib/btree_gist.sql

echo "= osmosis"
echo "- init db for osmosis"
psql $DB_NAME -f software/osmosis-latest/script/pgsimple_schema_0.6.sql
psql $DB_NAME -f software/osmosis-latest/script/pgsimple_schema_0.6_action.sql
#cd $ROOT_PATH/data/
#osmosis --read-xml $ROOT_PATH/data/europe.osm.bz2 --write-pgsql-dump
#cd pgimport
echo "- load db from osmosis"
#psql $DB_NAME < $ROOT_PATH/src/pgsql_simple_load.sql
pbzip2 -p4 -c -d data/planet-latest.osm.bz2 | osmosis --read-xml file="-" --write-pgsimp user="$DB_USER" database="$DB_NAME" password="$DB_PASS"

echo "finished import - next preprocess"
# read

echo "* Preprocessing data"
cd $ROOT_PATH
for i in src/sql/*.sql ; do echo "Executing $i ..." ; psql $DB_NAME < $i ; done

echo "=== Preprocessing finsished. Press key to continue"
read

echo "* SVN - Update style"
svn update conf.php render/

echo "List"
php $ROOT_PATH/src/wiki_data_conf.php
php src/wiki_create_indexes.php | psql $DB_NAME

export DB_NAME=gis

killall renderd

psql -d gisnew -c "alter database gis rename to gisold"
psql -d gisold -c "alter database gisnew rename to gis"
touch /osm/tiles/planet-import-complete

cd $ROOT_PATH
./software/mod_tile/mod_tile/renderd

cd $ROOT_PATH
./src/mcp
