#!/bin/bash

# This script is used in the live database
# The import happens in a new database called 'gisnew' 
# When everything is finished the old database 'gis' is renamed to 'gisold' (in
# case something went wrong, it can be drop later or when do_all_live is called
# the next time) and 'gisnew' renamed to 'gis'

export ROOT_PATH=/osm/osm
export SOFTWARE_PATH=/osm/osm/software
export DB_NAME=gisnew

echo "=== Starting Database reload. Press key to continue."
read

echo "* SVN - Update database import"
svn update src/

echo "* Download new OSM-File"
cd $ROOT_PATH/data
wget -N http://download.geofabrik.de/osm/europe.osm.bz2
wget -N -nv http://hypercube.telascience.org/~kleptog/processed_p.zip
wget -N -nv http://tileserv.openstreetmap.org/shoreline_300.tar.bz2

echo "* Importing to Database"
echo "- Shapefiles"
cd $ROOT_PATH/data
mkdir world_boundaries/
unzip processed_p.zip
mv coastlines/* world_boundaries/
rmdir coastlines
tar xjf shoreline_300.tar.bz2 -C world_boundaries

echo "- prepare osm2pgsql"
psql -d gis -c "drop database gisold"
psql -d gis -c "drop database gisnew"
psql -d gis -c "create database gisnew"
psql -d gisnew -c "create language plpgsql"
psql -d gisnew -f /usr/share/postgresql/8.4/contrib/postgis.sql
psql -d gisnew -f /usr/share/postgresql/8.4/contrib/_int.sql
psql -d gisnew -f /usr/share/postgresql/8.4/contrib/hstore.sql
psql -d gisnew -f /usr/share/postgresql/8.4/contrib/spatial_ref_sys.sql
psql -d gisnew -f /usr/share/postgresql/8.4/contrib/btree_gist.sql

echo "= osmosis"
echo "- init db for osmosis"
psql $DB_NAME < $ROOT_PATH/src/pgsql_simple_schema.sql
cd $ROOT_PATH/data/
osmosis --read-xml $ROOT_PATH/data/europe.osm.bz2 --write-pgsql-dump
cd pgimport
echo "- load db from osmosis"
psql $DB_NAME < $ROOT_PATH/src/pgsql_simple_load.sql

echo "finished import - next preprocess"
# read

echo "* Preprocessing data"
cd $ROOT_PATH
for i in src/sql/*.sql ; do echo "Executing $i ..." ; psql $DB_NAME < $i ; done

echo "=== Preprocessing finsished. Press key to continue"
read

echo "* SVN - Update style"
svn update conf.php render/

echo "List"
php $ROOT_PATH/src/wiki_data_conf.php
php src/wiki_create_indexes.php | psql $DB_NAME

export DB_NAME=gis

echo "* Update style-sheet"
export TMPDIR="/osm/`whoami`-style/`date +%Y%m%d-%H%M`"
mkdir -p $TMPDIR
echo "WIKI Style"
cd $ROOT_PATH
$ROOT_PATH/src/gen_mss_from_wiki.php
echo "BASE"
echo "Layers"
cd $ROOT_PATH/render
./gen_rotate_img.php
./gen_layer.php template_base.mml > base.mml
cascadenik-compile.py $ROOT_PATH/render/base.mml $ROOT_PATH/render/base_1.xml
./mapnik_merge_layer.php base_1.xml > base_2.xml
./mapnik_extract_datasource.php base_2.xml > base.xml
echo "PT"
cd $ROOT_PATH/render/img/rotate/src
for i in *.svg ; do convert -background none $i ../`echo $i | sed "s/svg$/png/"` ; done
cd $ROOT_PATH/render
cascadenik-compile.py $ROOT_PATH/render/overlay_pt.mml > $ROOT_PATH/render/overlay_pt.xml
$ROOT_PATH/src/update_xml $ROOT_PATH/render/overlay_pt.xml
./create_rotate_style
echo "CH"
cascadenik-compile.py $ROOT_PATH/render/overlay_ch.mml > $ROOT_PATH/render/overlay_ch.xml
$ROOT_PATH/src/update_xml $ROOT_PATH/render/overlay_ch.xml
echo "CAR"
render/gen_mml.php $ROOT_PATH/render/overlay_car > $ROOT_PATH/render/overlay_car_compiled.mml
cascadenik-compile.py $ROOT_PATH/render/overlay_car_compiled.mml > $ROOT_PATH/render/overlay_car.xml
$ROOT_PATH/src/update_xml $ROOT_PATH/render/overlay_car.xml

echo "Other"
cp $ROOT_PATH/render/overlay_services.template $ROOT_PATH/render/overlay_services.xml
$ROOT_PATH/src/update_xml $ROOT_PATH/render/overlay_services.xml

cp $ROOT_PATH/render/overlay_culture.template $ROOT_PATH/render/overlay_culture.xml
$ROOT_PATH/src/update_xml $ROOT_PATH/render/overlay_culture.xml

cp $ROOT_PATH/render/overlay_food.template $ROOT_PATH/render/overlay_food.xml
$ROOT_PATH/src/update_xml $ROOT_PATH/render/overlay_food.xml

cp $ROOT_PATH/render/shop.template $ROOT_PATH/render/shop.xml
$ROOT_PATH/src/update_xml $ROOT_PATH/render/shop.xml

cp $ROOT_PATH/render/agri_ind.template $ROOT_PATH/render/agri_ind.xml
$ROOT_PATH/src/update_xml $ROOT_PATH/render/agri_ind.xml

echo "=== Updated Style. Press key to continue"
read

echo "* SVN - Updating rest of code"
svn update

killall renderd

psql -d gisnew -c "alter database gis rename to gisold"
psql -d gisold -c "alter database gisnew rename to gis"
touch /osm/tiles/planet-import-complete

cd $ROOT_PATH
./software/mod_tile/mod_tile/renderd

cd $ROOT_PATH
./src/mcp
