#!/bin/bash

# This script is used in the live database
# The import happens in a new database called 'gisnew' 
# When everything is finished the old database 'gis' is renamed to 'gisold' (in
# case something went wrong, it can be drop later or when do_all_live is called
# the next time) and 'gisnew' renamed to 'gis'

export ROOT_PATH=/osm/osm
export SOFTWARE_PATH=/osm/osm/software
export DB_NAME=gisnew

echo "=== Starting Database reload. Press key to continue."
read

echo "* SVN - Update database import"
svn update src/

echo "* Download new OSM-File"
cd $ROOT_PATH/data
wget -N http://download.geofabrik.de/osm/europe.osm.bz2

echo "* Importing to Database"
echo "- prepare osm2pgsql"
cd $SOFTWARE_PATH/osm2pgsql
psql -d gis -c "drop database gisold"
psql -d gis -c "drop database gisnew"
psql -d gis -c "create database gisnew"
psql -d gisnew -c "create language plpgsql"
psql -d gisnew -f /usr/share/postgresql-8.3-postgis/lwpostgis.sql
psql -d gisnew -f /usr/share/postgresql/8.3/contrib/_int.sql
echo "= osm2pgsql"
./osm2pgsql -c -s -m -d $DB_NAME ~/data/europe.osm.bz2
echo "= osmosis"
echo "- init db for osmosis"
psql $DB_NAME < ~/src/pgsql_simple_schema.sql
cd $ROOT_PATH/data/
~skunkosm/software/osmosis-current/bin/osmosis --read-xml ~/data/europe.osm.bz2 --write-pgsql-dump
cd pgimport
echo "- drop unneeded geometry"
cut -f1-3 nodes.txt > nodes1.txt
mv nodes1.txt nodes.txt
echo "- load db from osmosis"
psql $DB_NAME < ~/src/pgsql_simple_load.sql

echo "finished import - next preprocess"
# read

echo "* Preprocessing data"
cd $ROOT_PATH
for i in src/sql/*.sql ; do echo "Executing $i ..." ; psql $DB_NAME < $i ; done

echo "=== Preprocessing finsished. Press key to continue"
read

echo "* SVN - Update style"
svn update conf.php render/

export DB_NAME=gis

echo "* Update style-sheet"
export TMPDIR="/osm/`whoami`-style/`date +%Y%m%d-%H%M`"
mkdir -p $TMPDIR
echo "BASE"
echo "Layers"
cd $ROOT_PATH/render
./gen_rotate_img.php
./gen_layer.php > base.mml
cascadenik-compile.py $ROOT_PATH/render/base.mml > $ROOT_PATH/render/base.xml
$ROOT_PATH/src/update_xml.pl $ROOT_PATH/render/base.xml
echo "PT"
cd $ROOT_PATH/render
convert -background none img/src/stop_p_back.svg img/stop_p_back.png
convert -background none img/src/stop_p_for.svg img/stop_p_for.png
convert -background none img/src/stop_n_back.svg img/stop_n_back.png
convert -background none img/src/stop_n_for.svg img/stop_n_for.png
convert -background none img/src/stop.svg img/stop.png
cascadenik-compile.py $ROOT_PATH/render/overlay_pt.mml > $ROOT_PATH/render/overlay_pt.xml
$ROOT_PATH/src/update_xml.pl $ROOT_PATH/render/overlay_pt.xml
./create_rotate_style
echo "CH"
cascadenik-compile.py $ROOT_PATH/render/overlay_ch.mml > $ROOT_PATH/render/overlay_ch.xml
$ROOT_PATH/src/update_xml.pl $ROOT_PATH/render/overlay_ch.xml
echo "CAR"
cascadenik-compile.py $ROOT_PATH/render/overlay_car.mml > $ROOT_PATH/render/overlay_car.xml
$ROOT_PATH/src/update_xml.pl $ROOT_PATH/render/overlay_car.xml
echo "WIKI Style"
cd $ROOT_PATH
$ROOT_PATH/src/gen_mss_from_wiki.php

echo "=== Updated Style. Press key to continue"
read

echo "* SVN - Updating rest of code"
svn update

killall renderd

psql -d gisnew -c "alter database gis rename to gisold"
psql -d gisold -c "alter database gisnew rename to gis"
touch /osm/tiles/planet-import-complete

cd $ROOT_PATH
./software/mod_tile/mod_tile/renderd
