#!/usr/bin/php
<?
$file="overlay_pt.xml";

$dom=new DOMDocument();
$dom->load($file);
     
$filters=$dom->getElementsByTagName("Filter");
for($i=0; $i<$filters->length; $i++) {
  $filter=$filters->item($i);

  if(eregi("\[(angle.*)\] = ([0-9]+)", $filter->nodeValue, $m)) {
    $rule=$filter->parentNode;
    $style=$rule->parentNode;
    print "Style '".$style->getAttribute("name")."'\n";
    print "$i $filter->nodeValue\n";
    print_r($m);
    $steps=$m[2];
    $replace=$m[0];
    $varname=$m[1];

    $list[]=array($style, $rule, $steps, $replace, $varname);
  }
}

foreach($list as $process) {
  $style=$process[0];
  $rule=$process[1];
  $steps=$process[2];
  $replace=$process[3];
  $varname=$process[4];

  $style->removeChild($rule);

  $point=$rule->getElementsByTagName("PointSymbolizer");
  $point=$point->item(0);
  $orig_file=$point->getAttribute("file");
  if(eregi("^(.*)\.png$", $point->getAttribute("file"), $m))
    $new_file=$m[1];

  for($a=0; $a<$steps; $a++) {
    $n=$rule->cloneNode(true);
    
    $f=$n->getElementsByTagName("Filter");
    $f=$f->item(0);
    $f->nodeValue=strtr($f->nodeValue, array($replace=>"[$varname] = $a"));
    
    $p=$n->getElementsByTagName("PointSymbolizer");
    $p=$p->item(0);
    if($orig_file) {
      $img=sprintf("%s_%02d.png", $new_file, $a);
      system("convert -background none -rotate ".(270+$a/$steps*360)." $orig_file $img");

      $p->setAttribute("file", sprintf($img, $a));
      $size=getimagesize(sprintf($img, $a));
      $p->setAttribute("height", $size[0]);
      $p->setAttribute("width", $size[1]);
    }

    $style->appendChild($n);
  }
}

$dom->save($file);
