#!/usr/bin/php
<?
$file="overlay_pt.xml";

$dom=new DOMDocument();
$dom->load($file);
 
# Indexing all files in img/
$d=opendir("img/rotate/");
while($r=readdir($d)) {
  if((substr($r, 0, 1)!=".")&&(substr($r, -4)==".png"))
    $img_files[]=$r;
}

$filters=$dom->getElementsByTagName("Filter");
for($i=0; $i<$filters->length; $i++) {
  $filter=$filters->item($i);

  if(eregi("\[(angle.*)\] = ([0-9]+)", $filter->nodeValue, $m)) {
    $rule=$filter->parentNode;
    $style=$rule->parentNode;
    $steps=$m[2];
    $replace=$m[0];
    $varname=$m[1];

    $list[]=array($style, $rule, $filter, $steps, $replace, $varname);
  }
}

foreach($list as $process) {
  $style=$process[0];
  $rule=$process[1];
  $filter=$process[2];
  $steps=$process[3];
  $replace=$process[4];
  $varname=$process[5];
  print "Style '".$style->getAttribute("name")."'\n";
  print "$filter->nodeValue\n";

  $style->removeChild($rule);

  $point=$rule->getElementsByTagName("PointSymbolizer");
  $point=$point->item(0);
  $orig_file=$point->getAttribute("file");

  foreach($img_files as $r) {
    $f=popen("compare -metric mae $orig_file img/rotate/$r /tmp/diff.png 2>&1", "r");
    $comp=fgets($f);
    pclose($f);
    if(substr($comp, 0, 5)=="0 (0)") {
      $orig_file="img/rotate/src/".substr($r, 0, -4).".svg";
    }
  }

  if(eregi("^(.*)\.png$", $point->getAttribute("file"), $m))
    $new_file=$m[1];

  print "$orig_file -> $new_file\n";
 
  for($a=0; $a<$steps; $a++) {
    $n=$rule->cloneNode(true);
    
    $f=$n->getElementsByTagName("Filter");
    $f=$f->item(0);
    $f->nodeValue=strtr($f->nodeValue, array($replace=>"[$varname] = $a"));
    
    $p=$n->getElementsByTagName("PointSymbolizer");
    $p=$p->item(0);
    if($orig_file) {
      $img=sprintf("%s_%02d.png", $new_file, $a);
      system("convert -background none -rotate ".(270+$a/$steps*360)." $orig_file $img");

      $p->setAttribute("file", sprintf($img, $a));
      $size=getimagesize(sprintf($img, $a));
      $p->setAttribute("height", $size[0]);
      $p->setAttribute("width", $size[1]);
    }

    $style->appendChild($n);
  }
}

$dom->save($file);
