#!/usr/bin/php
<?
require("render_conf.php");

$process_list=array();
$finished=0;
$index_places=0;
$index_layer=0;
$last_copy=time();

do {
#  print "* Checking processes ...\n";
  for($i=0; $i<$max_processes; $i++) {
    if((!$finished)&&
       ((!$process_list[$i])||
        (pcntl_waitpid($process_list[$i], &$status, WNOHANG)))) {
      $pid=pcntl_fork();
      if($pid==-1) {
	print "!! Could not fork\n";
      }
      elseif($pid) {
	$process_list[$i]=$pid;
	$index_layer++;
	if($index_layer>=sizeof($list_layer)) {
	  $index_places++;
	  $index_layer=0;
	  if($index_places>=sizeof($list_places))
	    $finished=1;
	}
      }
      else {
	$env=array(
	  "PLACE"          =>$list_places[$index_places][0],
	  "LAYER"          =>$list_layer[$index_layer][0],
	  "MINLON"         =>$list_places[$index_places][1],
	  "MINLAT"         =>$list_places[$index_places][2],
	  "MAXLON"         =>$list_places[$index_places][3],
	  "MAXLAT"         =>$list_places[$index_places][4],
	  "MINZOOM"        =>$list_layer[$index_layer][2],
	  "MAXZOOM"        =>(sizeof($list_layer[$index_layer])>3?$list_layer[$index_layer][3]:$list_places[$index_places][5]),
	  "MAPNIK_MAP_FILE"=>"{$dir_mapnik_config}/{$list_layer[$index_layer][1]}.xml",
          "MAPNIK_TILE_DIR"=>"{$dir_www_tiles}/{$list_layer[$index_layer][1]}/",
	  "MAPNIK_SYMBOLS_DIR"=>"/scratch/osm/software/mapnik/symbols",
	  "MAPNIK_WORLD_BOUNDARIES_DIR"=>"/scratch/osm/osm/data/world_boundaries",
	  "MAPNIK_DBNAME"=>"gis",
	  "MAPNIK_DBUSER"=>"skunkosm"
	);

        pcntl_exec("./generate_tiles.py", array(), $env);
      }
    }
  }

  if($copy_time+$last_copy<=time()) {
    print "* Copying tiles ...\n";
    system("cp -alf $dir_www_tiles/* $dir_copy_tiles/");
    $last_copy=time();
  }

  sleep(1);
} while(!$finished);

print "* Finished. Wating for completion\n";
pcntl_wait(&$status);
print "* Copying tiles ...\n";
system("cp -alf $dir_www_tiles/* $dir_copy_tiles/");
