<?
$lang_str["importance:name"]="Belangrijkheid";
$lang_str["importance:global"]="wereldwijd";
$lang_str["importance:international"]="internationaal";
$lang_str["importance:national"]="nationaal";
$lang_str["importance:regional"]="regionaal";
$lang_str["importance:urban"]="stedelijk";
$lang_str["importance:suburban"]="voorstedelijk";
$lang_str["importance:local"]="lokaal";
