<?
$lang_str["importance:name"]="Importanza";
$lang_str["importance:global"]="globale";
$lang_str["importance:international"]="internazionale";
$lang_str["importance:national"]="nazionale";
$lang_str["importance:regional"]="regionale";
$lang_str["importance:urban"]="urbana";
$lang_str["importance:suburban"]="suburbana";
$lang_str["importance:local"]="locale";
