#!/usr/bin/php
<?
// Found root path of script
$path=$argv[0];
if(is_link($path))
  $path=readlink($path);
$path=realpath(dirname($path)."/../..");
chdir($path);

include "conf.php";
$modulekit_load[]="state_info";
include "modulekit/loader.php";

function out_of_date() {
  global $root_path;

  $state_date=state_info_date();
  $now_date=new DateTime("now", new DateTimeZone("UTC"));

  $diff=$now_date->diff($state_date);
  $diff=$diff->format("%a:%H:%i:%s");
  $diff=explode(":", $diff);
  $diff=($diff[0]/1.0+$diff[1]/24.0+$diff[2]/1440+$diff[3]/86400.0);
  return $diff;
}

switch($argv[1]) {
  case 'config':
    print <<<EOT
graph_title DB out of date
graph_vlabel days
graph_category other
graph_info This graph shows how many days the database of OSB lacks behind OpenStreetMap
osm.label current

EOT;
    break;
  default:
    print "osm.value ".out_of_date()."\n";
}
