#!/usr/bin/php
<?
include "/home/osm/conf.php";
include_once "/home/osm/conf.php";

function out_of_date() {
  global $root_path;
  @$state=file_get_contents("$root_path/data/updates/state.txt");
  if(!$state) {
    print "Could not open state file\n";
    exit;
  }

  $state=explode("\n", $state);
  $state_date=null;
  foreach($state as $state_line) {
    if(preg_match("/^timestamp=(.*)$/", $state_line, $m)) {
      $state_date=stripslashes($m[1]);
    }
  }

  if(!$state_date) {
    print "Could not parse state date\n";
    exit;
  }

  $state_date=new DateTime($state_date);
  $now_date=new DateTime("now", new DateTimeZone("UTC"));

  $diff=$now_date->diff($state_date);
  $diff=$diff->format("%a:%H:%i:%s");
  $diff=explode(":", $diff);
  $diff=($diff[0]/1.0+$diff[1]/24.0+$diff[2]/1440+$diff[3]/86400.0);
  return $diff;
}

switch($argv[1]) {
  case 'config':
    print <<<EOT
graph_title DB out of date
graph_vlabel days
graph_category other
graph_info This graph shows how many days the database of OSB lacks behind OpenStreetMap
osm.label current

EOT;
    break;
  default:
    print "osm.value ".out_of_date()."\n";
}
