#!/usr/bin/php
<?
$verbose=false;

if(sizeof($argv)<2) {
  print "What language do you want to check?\n";
  exit;
}

$check=$argv[1];

function lang() {
}

$lang_str=array();
@include "www/lang/en.php";
@include "www/lang/tags_en.php";
$d=opendir("www/plugins");
while($f=readdir($d))
  @include "www/plugins/$f/lang_en.php";
$en_lang=$lang_str;

$lang_str=array();
@include "www/lang/{$check}.php";
@include "www/lang/tags_{$check}.php";
while($f=readdir($d))
  @include "www/plugins/$f/lang_{$check}.php";
$check_lang=$lang_str;

$missing=array();
$same=array();
foreach($en_lang as $k=>$v) {
  if(!isset($check_lang[$k])) {
    $missing[]=$k;
  }
  else if($check_lang[$k]==$en_lang[$k]) {
    $same[]=$k;
  }
}

$deprecated=array();
foreach($check_lang as $k=>$v) {
  if(!isset($en_lang[$k])) {
    $deprecated[]=$k;
  }
}

print "* ".sizeof($missing)." Strings missing.\n";
if($verbose)
  print implode(", ", $missing)."\n";

print "* ".sizeof($deprecated)." Strings deprecated (defined in translation, but not in check language):\n";
if($verbose)
  print implode(", ", $deprecated)."\n";

print "* ".sizeof($same)." Strings not translated (or translation equal to original language):\n";
if($verbose)
  print implode(", ", $same)."\n";
