#!/usr/bin/php
<?
include "conf.php";
include "inc/sql.php";
$sql=pg_connect("dbname=$db_name user=$db_user password=$db_passwd host=$db_host");

function change_next() {
  global $db_name;
  global $db_passwd;
  global $root_path;
  $working_dir="$root_path/data/updates";

  if(!file_exists("$working_dir/state.txt")) {
    print "ERROR: state_file does not exist. Please create the working directory data/updates/. See http://wiki.openstreetmap.org/wiki/Minutely_Mapnik for details.\n";
    exit;
  }

  $descriptors=array(
    0=>array("pipe", "r"),
    1=>array("pipe", "w"),
    2=>array("pipe", "w"));

  $command="osmosis --read-replication-interval workingDirectory=$working_dir --simplify-change --write-pgsql-change database=$db_name password=$db_passwd";

  $p=proc_open($command, $descriptors, $pipes, null, array("JAVACMD_OPTIONS"=>"-Xmx512M"));
//  if($stdin)
//    fwrite($pipes[0], $stdin);
  $ret=stream_get_contents($pipes[1]);
  $error=stream_get_contents($pipes[2]);
  
  fclose($pipes[0]);
  fclose($pipes[1]);
  fclose($pipes[2]);
  $exit=proc_close($p);

  print "$ret<stderror>$error\n";

  if($exit==0)
    return 1;
  
  return 0;
}

while(1) {
  $ret2=change_next();

  if(($ret2==0)) {
    print "Error? Let's wait a little ...\n";
    sleep(30);
  }

}
