#!/usr/bin/php
<?
include "conf.php";
include "inc/hooks.php";
include "inc/lock.php";
include "inc/tags.php";
include "inc/sql.php";
include "inc/debug.php";
include "inc/category.php";
include "inc/categories.php";
include "inc/process_category.php";
include "inc/functions.php";
include "inc/css.php";
$sql=pg_connect("dbname=$db_name user=$db_user password=$db_passwd host=$db_host");

$conf=fopen("$root_path/data/renderd.conf", "w");

$template=file_get_contents("$root_path/src/renderd.conf.template");
fwrite($conf, $template);

$d=opendir("$lists_dir");
while($f=readdir($d)) {
  if(preg_match("/(.*)\.xml$/", $f, $m)) {
    if(!file_exists("$lists_dir/$f.renderd")) {
      print "compiling $m[1]\n";
      $x=new category($m[1]);
      $x->compile();
    }

    $conf_part=file_get_contents("$lists_dir/$f.renderd");
    fwrite($conf, $conf_part);
  }
}
closedir($d);

fclose($conf);
