#!/usr/bin/php
<?
include "conf.php";
include "inc/sql.php";

function save($file, $data, $parent) {
  print "$file $data[commit] $parent\n";
  print_r($data);
}

chdir($lists_dir);
$d=opendir(".");
while($f=readdir($d)) {
  if(preg_match("/(.*)\.xml$/", $f, $m)) {
    $file=$m[1];
    print "Processing file '$file'\n";

    $flog=popen("git log --pretty=short $file.xml", "r");
    $last=null;
    while($log=fgets($flog)) {
      $log=trim($log);

      if(preg_match("/^commit (.*)$/", $log, $m)) {
	if($last!=null)
	  save($file, $last, $m[1]);
	$last=array("commit"=>$m[1]);
      }
      elseif(preg_match("/^Author:.*<(.*)@/", $log, $m)) {
	$last["user"]=$m[1];
      }
      elseif(preg_match("/^Date: *(.*)$@/", $log, $m)) {
	$last["date"]=$m[1];
      }
      elseif($log=="") {
      }
      else {
	if(isset($last["comment"]))
	  $last["comment"].="\n";
	else
	  $last["comment"]="";

	$last["comment"].="$log";
      }
    }

    save($file, $last, null);
    pclose($flog);
  }
}
