#!/usr/bin/php
<?
include "conf.php";
include "inc/hooks.php";
include "inc/plugins.php";
include "inc/lock.php";
include "inc/number.php";
include "inc/tags.php";
include "inc/sql.php";
include "inc/debug.php";
include "inc/category.php";
include "inc/categories.php";
include "inc/process_category.php";
include "inc/functions.php";
include "inc/dom.php";
include "inc/css.php";
include "inc/postgis.php";
include "inc/git_obj.php";
include "inc/data_dir.php";
include "inc/icon.php";
include "gen_renderd_conf.php";
$sql=pg_connect("dbname=$db_name user=$db_user password=$db_passwd host=$db_host");
plugins_init("mcp");
call_hooks("mcp_start");

function restart_renderd() {
  global $root_path;

  system("killall renderd");
  gen_renderd_conf();
  chdir($root_path);
  system("src/ap2restart");
  system("software/mod_tile/renderd");
}

function compile($cat_id) {
  $x=new category($cat_id);
  $x->compile();
  restart_renderd();
}

function mcp_process($todo) {
  $todo=explode(" ", $todo);

  switch($todo[0]) {
    case "restart":
      restart_renderd();
      break;
    case "compile":
      compile($todo[1]);
      break;
    default:
      print "didn't understand ".implode(" ", $todo)."\n";
  }
  return 1;
}

declare(ticks=1);
function mcp_sig_handler($signo) {
  global $fifo;
  global $fifo_path;

  switch($signo) {
    case SIGTERM:
    case SIGINT:
      print "exiting\n";
      fclose($fifo);
      unlink($fifo_path);
      exit;
  }
}

umask(0);
posix_mkfifo($fifo_path, 0666);
$fifo=fopen($fifo_path, "r+");

$tmp_dir="$root_path/tmp/".Date("Ymd-Hi");
print "Creating temporary directory $tmp_dir\n";
mkdir($tmp_dir);

pcntl_signal(SIGTERM, "mcp_sig_handler");
pcntl_signal(SIGINT,  "mcp_sig_handler");

restart_renderd();

while(1) {
  $stream_read=array($fifo);
  $stream_write=array();
  $stream_except=array();
  stream_select($stream_read, $stream_write, $stream_except, 1);

  foreach($stream_read as $str) {
    if($str==$fifo) {
      $todo=trim(fgets($fifo));
      mcp_process($todo);
    }
  }
}
