#!/usr/bin/php
<?
$root_path=$_ENV['ROOT_PATH'];
$file=$argv[1];

$full_text="";
$f=fopen($file, "r");
$w=fopen("/tmp/tmp.xml", "w");

$tr=array();
$tr["__DBNAME__"]=$_ENV['DB_NAME'];

while($r=fgets($f)) {
  $r=strtr($r, $tr);

  while(preg_match("/<InsertLayer name=\"([A-Za-z:_]+)\" \/>/", $r, $m)) {
    $p1=strpos($r, $m[0]);
    
    fwrite($w, substr($r, 0, $p1));
    $f1=fopen("$root_path/render/$m[1].layer", "r");

    while($r1=fgets($f1)) {
      fwrite($w, $r1);
    }

    fclose($f1);
    $r=substr($r, $p1+strlen($m[0]));
  }

  fwrite($w, $r);
}

fclose($f);
fclose($w);

rename("/tmp/tmp.xml", $file);
